# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 007aa2a73e9b53a7977bd5b2b69e3fd7a35dd23cddc388ea28a7ab0c8c53005a1af2d5e71e2e1ed6a21c63ebd07ac993006a8eb87a7eaf8c47e4686285cc34f0

test:
  secret_key_base: 7bed5f437555ff976a1402189188711a2e7cdcb8a253b4e1d95d24a64d8d3af4cca30c63e0ab34ca24c63ef86e1b9b9ea01110272a74eb2000791e41c017d4ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
